version: '3'

services:
  nginx:
    image: nginx:1.13
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    ports:
      - 8082:80
      - 443:443
    depends_on:
      - app
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: docker.{{.Name}}
 
  mysql:
    build: ./mysql
    environment:
      MYSQL_DATABASE: sample
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3306
    restart: always

  redis:
    image: redis:latest
    ports:
      - 6379:6379
  
  app:
    restart: always
    build: ./app
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: sample
      DB_USERNAME: root
      DB_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DATABASE: 0
    ports:
      - 8081:8080
    depends_on:
      - mysql
      - fluentd

  elasticsearch:
    image: elasticsearch:5.6-alpine
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearch/jvm.options:/usr/share/elasticsearch/config/jvm.options
    
  kibana:
    image: kibana:5.6
    ports: 
    - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
    - elasticsearch

  fluentd:
    build: ./fluentd
    ports:
      - 24224:24224
      - 24220:24220
      - 24224:24224/udp
    depends_on:
    - elasticsearch
