version: '3'
services:
  nginx:
    image: nginx:1.13
    restart: always
    ports:
      - 8082:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
 
  mysql:
    build: ./mysql
    environment:
      MYSQL_DATABASE: sample
      MYSQL_ROOT_PASSWORD: password
    expose:
      - "3306"
    ports:
      - "3307:3306"
    restart: always
  
  app:
    restart: always
    build: ./app
    volumes:
      - ./app:/app
    expose:
      - "8080"
    ports:
      - "8081:8080"
    depends_on:
      - mysql
