version: '3'
services:
  nginx:
   container_name: spring-nginx
   image: nginx:1.13
   restart: always
   ports:
   - 8081:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   depends_on:
   - app
 
  mysql:
   container_name: spring-mysql
   image: mysql/mysql-server:5.7
   environment:
    MYSQL_DATABASE: test
    MYSQL_ROOT_PASSWORD: hellokoding
    MYSQL_ROOT_HOST: '%'
   ports:
   - "3306:3306"
   restart: always
  
  app:
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
    expose:
      - "8080"
    command: bash -c "./gradlew build --continuous & ./gradlew bootRun"
    depends_on:
      - mysql
