version: '3'

services:
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 8082:80
      - 443:443
    depends_on:
      - app
 
  mysql:
    build: ./mysql
    environment:
      MYSQL_DATABASE: sample
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3306
    restart: always

  redis:
    image: redis:latest
    ports:
      - 6379:6379
  
  app:
    restart: always
    build: ./app
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: sample
      DB_USERNAME: root
      DB_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DATABASE: 0
    ports:
      - 8081:8080
    depends_on:
      - mysql
